Repository ETIOct2020Team3/ETI-Group-Assignment-1, pull requests merged in 2021-01, with the labels that each got.

#25 fix #16
  __pycache__/Menus.cpython-38.pyc
  __pycache__/classes.cpython-38.pyc
  __pycache__/outdoorMenu.cpython-38.pyc
  main.py
  outdoor-menu.py
  outdoorMenu.py
Labels: enhancement, good first issue

#26 fix #11
  .gitignore
  combatMenuFunctions.py
  main.py
Labels: enhancement

#40 Fix #37 Fix #12
  Menus.py
  __pycache__/Menus.cpython-38.pyc
  __pycache__/classes.cpython-38.pyc
  combatMenuFunctions.py
  main.py
Labels: bug

#43 fix #42
  main.py
Labels: bug
